# nfl/build_position_map_by_range.py
from __future__ import annotations

from typing import Any, Dict, Optional
import json
import time

import requests


ESPN_CORE_BASE = "https://sports.core.api.espn.com/v2/sports/football/leagues/nfl"
POSITION_URL_TMPL = f"{ESPN_CORE_BASE}/positions/{{num}}"


_SESSION = requests.Session()


def _get_json(url: str, *, params: Optional[dict] = None, timeout: int = 30) -> dict:
    r = _SESSION.get(url, params=params, timeout=timeout)
    # ESPN sometimes returns JSON even on 404, but status might still be 404.
    # We still want the JSON body for {"error": {...}}.
    try:
        return r.json()
    except Exception:
        # If something truly non-JSON happens, treat as empty
        return {}


def _is_not_found(payload: Any) -> bool:
    """
    ESPN's "no instance found" typically returns:
      {"error": {"message": "no instance found", "code": 404}}
    Sometimes status code is 404; sometimes you still get JSON either way.
    """
    if not isinstance(payload, dict):
        return True
    err = payload.get("error")
    if isinstance(err, dict):
        code = err.get("code")
        msg = (err.get("message") or "").lower()
        if code == 404 or "no instance found" in msg:
            return True
    return False


def build_position_id_map_by_range(
    *,
    start: int = 1,
    end: int = 100,
    timeout: int = 30,
    sleep_s: float = 0.02,
    out_json: str = "nfl/data/players/position_map.json",
    out_py: str = "nfl/data/position_map.py",
) -> Dict[str, Dict[str, Any]]:
    """
    Hits:
      /positions/{num}
    for num in [start, end] inclusive.

    If found, payload looks like:
      {"id":"78","name":"Long Snapper","abbreviation":"LS", ...}
    If not found:
      {"error":{"message":"no instance found","code":404}}

    Writes:
      - JSON mapping
      - Python module mapping

    Returns:
      dict[position_id] -> {"name":..., "abbreviation":..., "displayName":..., "parent_id":..., "leaf":...}
    """
    mapping: Dict[str, Dict[str, Any]] = {}

    params = {"lang": "en", "region": "us"}  # keep consistent

    for num in range(int(start), int(end) + 1):
        url = POSITION_URL_TMPL.format(num=num)
        payload = _get_json(url, params=params, timeout=timeout)

        if _is_not_found(payload):
            if sleep_s:
                time.sleep(sleep_s)
            continue

        if not isinstance(payload, dict):
            if sleep_s:
                time.sleep(sleep_s)
            continue

        pos_id = str(payload.get("id") or num)

        parent_id = None
        parent = payload.get("parent")
        if isinstance(parent, dict) and isinstance(parent.get("$ref"), str):
            # Parent ref ends with /positions/{id}?...
            # We can just take the last path segment before ?.
            ref = parent["$ref"]
            # normalize to https in case it returns http
            if ref.startswith("http://"):
                ref = "https://" + ref[len("http://") :]
            # cheap parse:
            try:
                parent_id = ref.split("/positions/")[1].split("?")[0].split("/")[0]
            except Exception:
                parent_id = None

        mapping[pos_id] = {
            "name": payload.get("name") or "",
            "displayName": payload.get("displayName") or "",
            "abbreviation": payload.get("abbreviation") or "",
            "leaf": bool(payload.get("leaf")) if "leaf" in payload else None,
            "parent_id": parent_id,
            "ref": (payload.get("$ref") or ""),
        }

        if sleep_s:
            time.sleep(sleep_s)

    # Write JSON for inspection
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(mapping, f, indent=2, sort_keys=True)

    # Write Python module for importing
    py_contents = (
        "# Auto-generated from ESPN core NFL positions endpoint\n"
        f"# Source template: {POSITION_URL_TMPL}\n"
        f"# Generated by scanning range [{start}, {end}] with lang=en, region=us\n\n"
        "from __future__ import annotations\n\n"
        "POSITION_ID_TO_INFO: dict[str, dict[str, object]] = "
        + repr(mapping)
        + "\n\n"
        "def position_name(position_id: str) -> str:\n"
        "    info = POSITION_ID_TO_INFO.get(str(position_id)) or {}\n"
        "    return str(info.get('name') or '')\n\n"
        "def position_abbr(position_id: str) -> str:\n"
        "    info = POSITION_ID_TO_INFO.get(str(position_id)) or {}\n"
        "    return str(info.get('abbreviation') or '')\n"
    )
    with open(out_py, "w", encoding="utf-8") as f:
        f.write(py_contents)

    print(f"Found {len(mapping)} positions in range [{start}, {end}]")
    print(f"Wrote {out_json}")
    print(f"Wrote {out_py}")
    return mapping


if __name__ == "__main__":
    # tweak sleep_s upward (e.g. 0.05) if you want to be extra gentle to ESPN
    build_position_id_map_by_range(start=1, end=100, timeout=30, sleep_s=0.02)